### ISSUE TITLE
build fails on 7.8

### ISSUE THREAD

**Issue by cartazio** [Deewiant/list-tries#1]
https://hackage.haskell.org/package/list-tries-0.6.0/reports/1 

i think that 0.6 is still < 7.10, i'll use my trustee powers to limit it for now. https://hackage.haskell.org/package/list-tries-0.6.0/revisions/ (I / you can always revert those bounds, but seems like the right thing to do )

you should also add a .travis.yml and try out travis CI for easily testing the range of GHC's you wish to support before pushign to hackage! :) 

https://github.com/hvr/multi-ghc-travis is a good template to use
may OSS haskell projects use that or some customization thereof, eg my hblas package  https://github.com/wellposed/hblas/blob/master/.travis.yml 
or the lens project https://github.com/ekmett/lens/blob/master/.travis.yml both use it in some form

**Comment by Deewiant** [comment]
The build report is actually about "ghc-7.8.3", as it says at the top. I was in a bit of a hurry and made 0.6 build /only/ on 7.10, apparently. Will fix.

**Comment by Deewiant** [comment]
Should be fixed by 639e2938e059e04b2ba4ac371676df362920e90e, which is in 0.6.1 now.

I should probably have a look at that Travis stuff at some point.

**Comment by Deewiant** [comment]
Also edited the metadata for 0.6.0 so that it depends on `base >= 4.8`...

**Comment by cartazio** [comment]
Great! Thanks for fixing up things!
